services:
    moodle-api:
        build: .
        image: ghcr.io/dotnaos/moodle-services:latest
        command: ['serve', '--addr', ':8080']
        environment:
            - PORT=8080
            - MOODLE_HOME=/data
            - MOODLE_USERNAME=${MOODLE_USERNAME}
            - MOODLE_PASSWORD=${MOODLE_PASSWORD}
        ports:
            - '8080:8080'
        volumes:
            - ${HOME}/.moodle:/data
